[versions]
scalardb = "3.17.3"
jackson = "2.18.6"
slf4j = "2.0.17"
logback = "1.5.32"
mockito = "5.23.0"
assertj = "3.27.6"
sqlite-jdbc = "3.53.0.0"
spotless = "8.4.0"
spotbugs-plugin = "6.5.1"
errorprone = "2.49.0"
errorprone-plugin = "5.1.0"
nullaway = "0.13.3"
nullaway-plugin = "3.0.0"
findsecbugs = "1.14.0"
jspecify = "1.0.0"

[libraries]
scalardb = { module = "com.scalar-labs:scalardb", version.ref = "scalardb" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
findsecbugs-plugin = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
nullaway = { id = "net.ltgt.nullaway", version.ref = "nullaway-plugin" }
